#ifndef CONFIG_H_INCLUDED
#define CONFIG_H_INCLUDED

#define CONFIG_REQUEST_MAX 200
#define CONFIG_SERVER_LOCATION "3000"
#define CONFIG_THREAD_COUNT 5

#define CONFIG_UNI_START 1072

#define CONFIG_MAX_TIME      30
#define CONFIG_MAX_RESPONCE  40

#define CONFIG_DICT_PATH "dict.utf8"

#endif
